name: health check flow

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  NOMAL_WEBHOOK_URL: ${{ secrets.NOMAL_WEBHOOK_URL }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout result branch
        uses: actions/checkout@v4
        with:
          ref: result
          path: result-data
        continue-on-error: true

      - name: Run monitor
        run: |
          mkdir -p result
          
          if [ -f result-data/result.json ]; then
            cp result-data/result.json result/result.json
            echo "Previous history loaded."
          else
            echo "No previous history found. Starting new."
          fi
          
          node scripts/checks/index.js

      - name: Commit & Push result
        run: |
          git config user.name "GitupdatehubBot"
          git config user.email "gitupdatehubbot@users.noreply.github.com"
      
          # result ブランチが存在するか確認してなければ作る
          if git ls-remote --exit-code --heads origin result; then
            echo "result branch exists. Checking out."
            git checkout -B result origin/result
          else
            echo "result branch does not exist. Creating..."
            git checkout -B result
          fi
      
          # result ディレクトリを反映
          mkdir -p result-data
          cp -r result/* result-data/
      
          git add result-data
          if ! git diff --cached --exit-code --quiet; then
            git commit -m "Update monitor results $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin HEAD:result
          else
            echo "No changes to commit"
          fi


  deploy:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      
      - name: Checkout result
        uses: actions/checkout@v4
        with:
          ref: result
          path: result

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: node scripts/build/index.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./final_html
          publish_branch: gh-pages
