name: Validate setting.json

on:
  push:
    paths:
      - "setting.json"
      - "scripts/setting_check/index.js"
  pull_request:
    paths:
      - "setting.json"
      - "scripts/setting_check/index.js"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate setting.json
        run: |
          node scripts/setting_check/index.js
